# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxRORn_bHC-o9vasPHFoLDK54RTsyonw
"""

#Preprocessing the data
NUM_CLASSES = 2
BATCH_SIZE = 4
EPOCHS = 25

print("Building highly optimized parallel tf.data pipelines...")

def prepare_sample(filepath, bboxes, c_ids):
    #Handles image loading, decoding, and normalization on-the-fly.
    img = tf.io.read_file(filepath)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, (320, 320))
    img = tf.cast(img, tf.float32) / 255.0  # Normalize pixel space

    return img, {"boxes": bboxes, "classes": c_ids}

def build_pipeline(dataset_split):
    file_paths = []
    all_boxes = []
    all_classes = []

    # Generates exact zero-indexed mapping: {"Person": 0, "Car": 1}
    class_to_id = {cls_name: idx for idx, cls_name in enumerate(TARGET_CLASSES)}

    for sample in dataset_split:
        if not hasattr(sample, "ground_truth") or sample.ground_truth is None:
            continue

        bboxes = []
        c_ids = []

        for det in sample.ground_truth.detections:
            if det.label in class_to_id:
                xmin, ymin, w, h = det.bounding_box
                # Map FiftyOne bounding format to TensorFlow normalized format
                bboxes.append([ymin, xmin, ymin + h, xmin + w])
                c_ids.append(class_to_id[det.label])

        if len(bboxes) == 0:
            continue

        # Pad up to 10 instances using -1 to explicitly flag background slots
        while len(bboxes) < 10:
            bboxes.append([0.0, 0.0, 0.0, 0.0])
            c_ids.append(-1)

        # Append data slices to memory trackers
        file_paths.append(sample.filepath)
        all_boxes.append(bboxes[:10])
        all_classes.append(c_ids[:10])

    # Convert to explicit signed integer formats to support negative padding indices safely
    dataset = tf.data.Dataset.from_tensor_slices((
        file_paths,
        np.array(all_boxes, dtype=np.float32),
        np.array(all_classes, dtype=np.int32)  # Signed int handles -1 cleanly
    ))

    # Parallel mapping over CPU threads
    dataset = dataset.map(
        lambda fp, b, c: prepare_sample(fp, b, c),
        num_parallel_calls=tf.data.AUTOTUNE
    )

    return dataset

# Compile parallel hardware streaming pipelines
tf_train_data = build_pipeline(train_dataset).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
tf_test_data = build_pipeline(test_dataset).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print("Scalable parallel pipelines compiled successfully for 2 classes!")