# -*- coding: utf-8 -*-
"""testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxRORn_bHC-o9vasPHFoLDK54RTsyonw
"""

#model testing
import matplotlib.pyplot as plt

print("\nGenerating Convergence Curves from SSD Training History...")
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

# Box Loss Plot
ax1.plot(history.history.get('boxes_loss', history.history.get('loss', [])),
         label='Train Box Loss', color='royalblue', linewidth=2.5)
if 'val_boxes_loss' in history.history:
    ax1.plot(history.history['val_boxes_loss'], label='Val Box Loss', color='orange', linestyle='--', linewidth=2)
ax1.set_title('Localization Anchor Convergence', fontsize=13, weight='bold')
ax1.set_xlabel('Epochs Run'); ax1.set_ylabel('Loss Error Value (Huber)')
ax1.legend(loc='upper right'); ax1.grid(True, linestyle=':', alpha=0.6)

# Class Loss Plot
if 'classes_loss' in history.history:
    ax2.plot(history.history['classes_loss'], label='Train Class Loss', color='forestgreen', linewidth=2.5)
    if 'val_classes_loss' in history.history:
        ax2.plot(history.history['val_classes_loss'], label='Val Class Loss', color='crimson', linestyle='--', linewidth=2)
else:
    ax2.plot(history.history['loss'], label='Total Compound Loss', color='purple', linewidth=2.5)
ax2.set_title('Label Categorization Convergence', fontsize=13, weight='bold')
ax2.set_xlabel('Epochs Run'); ax2.set_ylabel('Loss Error Value (CrossEntropy)')
ax2.legend(loc='upper right'); ax2.grid(True, linestyle=':', alpha=0.6)

plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns

print("\nCalculating model performance metrics on test dataset...")

all_true_classes = []
all_pred_classes = []

# Loop through the test data batches
for images, targets in tf_test_data:
    true_boxes = targets["boxes"].numpy()
    true_classes = targets["classes"].numpy()

    # Run model inference
    preds = model.predict(images, verbose=0)
    pred_classes = np.argmax(preds["classes"], axis=-1)

    # Flatten the batches to look at individual object slots
    for b in range(images.shape[0]):
        for o in range(10): # 10 maximum slots per image
            t_cls = true_classes[b, o]
            p_cls = pred_classes[b, o]
            if t_cls == -1:
                continue

            all_true_classes.append(t_cls)
            all_pred_classes.append(p_cls)

# Convert compiled lists to numpy arrays
y_true = np.array(all_true_classes)
y_pred = np.array(all_pred_classes)


print("\n=== DETAILED PERFORMANCE METRICS ===")
# Explicitly mapping to your 2 active indices (0: Person, 1: Car)
all_indices = [0, 1]
class_names = TARGET_CLASSES  # ["Person", "Car"]

report = classification_report(
    y_true,
    y_pred,
    labels=all_indices,       # Force metrics tracking for exactly your 2 classes
    target_names=class_names,
    zero_division=0
)
print(report)


print("\nGenerating Confusion Matrix Heatmap...")
# Calculate matrix strictly across your 2 active indices
cm = confusion_matrix(y_true, y_pred, labels=all_indices)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)
plt.title('Person vs Car Confusion Matrix Heatmap', fontsize=12)
plt.xlabel('Predicted Label', fontsize=11)
plt.ylabel('True Label', fontsize=11)
plt.tight_layout()
plt.show()