# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VxRORn_bHC-o9vasPHFoLDK54RTsyonw
"""

# Model training
import tensorflow as tf

inputs = tf.keras.Input(shape=(320, 320, 3))
x = tf.keras.applications.mobilenet_v2.preprocess_input(inputs * 255.0)

base_model = tf.keras.applications.MobileNetV2(
    input_shape=(320, 320, 3), input_tensor=x, include_top=False, weights='imagenet'
)

# Unfreeze the backbone so it can learn custom object shapes
base_model.trainable = True

# Refreeze only the bottom layers to protect foundational features (edges, textures)
for layer in base_model.layers[:-40]:
    layer.trainable = False

features = base_model.output

# SSD Local Spatial Detectors
conv_loc = tf.keras.layers.Conv2D(256, (3, 3), padding='same', activation='relu')(features)
conv_loc = tf.keras.layers.BatchNormalization()(conv_loc)

pool_spatial = tf.keras.layers.GlobalAveragePooling2D(keepdims=True)(conv_loc)
up_to_anchors = tf.keras.layers.UpSampling2D(size=(10, 1))(pool_spatial)

# Bounding Box Anchor Head
box_conv = tf.keras.layers.Conv2D(4, (1, 1), padding='same')(up_to_anchors)
box_output_layer = tf.keras.layers.Reshape((10, 4))(box_conv)
box_output = tf.keras.layers.Activation('sigmoid', name="boxes")(box_output_layer)

# Classification Head
class_conv = tf.keras.layers.Conv2D(NUM_CLASSES, (1, 1), padding='same')(up_to_anchors)
class_output_layer = tf.keras.layers.Reshape((10, NUM_CLASSES))(class_conv)
class_output = tf.keras.layers.Activation('softmax', name="classes")(class_output_layer)

# Instantiate the final Functional Model
model = tf.keras.Model(inputs=inputs, outputs={"boxes": box_output, "classes": class_output})

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5, clipnorm=1.0),
    loss={
        "boxes": tf.keras.losses.Huber(),
        "classes": tf.keras.losses.SparseCategoricalCrossentropy(ignore_class=-1)
    },
    loss_weights={"boxes": 40.0, "classes": 1.0}
)

print("Fine-Tuning SSD Model Compiled Successfully with Pure Keras Layers!")

history = model.fit(
    tf_train_data,
    validation_data=tf_test_data,
    epochs=EPOCHS
)